# Enable the starloom plugin
plugins = ["starloom.linting"]

# Enable all rules by default
select = ["ALL"]

# Custom rule to catch src imports
[tool.ruff.rules]
src-import = { enabled = true }

[tool.ruff.rules.src-import]
message = "Do not import from 'src' directory. Use the package name directly." 